image: node:latest

# Pipeline
stages:
  - install
  - build
  - test
  - deploy

variables:
  npm_config_cache: '$CI_PROJECT_DIR/.npm'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

cache:
  key:
    files:
      - package.json
  paths:
    - .npm
    - cache/Cypress
    - node_modules

# Jobs
install_dependencies:
  stage: install
  script:
    - npm ci --cache .npm --prefer-offline
  artifacts:
    paths:
      - node_modules/

bundle_app:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/

components_test:
  image: cypress/browsers:node14.16.0-chrome90-ff88
  stage: test
  only:
    - main
  script:
    - echo "Run tests in headless mode"
    - npm run start:ci:components

e2e_test:
  image: cypress/browsers:node14.16.0-chrome90-ff88
  stage: test
  only:
    - main
  script:
    - echo "Run tests in headless mode"
    - npm run start:ci

netlify:
  stage: deploy
  only:
    - main
  script:
    - echo "Visit this project at https://imovies-zihan.netlify.app/"
